# Generated by Django 4.2.2 on 2023-07-21 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ots1', '0003_rename_questions_qestion_ques'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Qestion',
            new_name='Question',
        ),
    ]
