# Generated by Django 4.2.2 on 2023-07-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ots1', '0004_rename_qestion_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ques',
            field=models.TextField(verbose_name=255),
        ),
    ]
